// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.2
// source: v1/delete-recipe-translation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRecipeTranslationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId    string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	RequesterId string `protobuf:"bytes,2,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	Language    string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *DeleteRecipeTranslationRequest) Reset() {
	*x = DeleteRecipeTranslationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_delete_recipe_translation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecipeTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeTranslationRequest) ProtoMessage() {}

func (x *DeleteRecipeTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_recipe_translation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeTranslationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecipeTranslationRequest) Descriptor() ([]byte, []int) {
	return file_v1_delete_recipe_translation_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRecipeTranslationRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *DeleteRecipeTranslationRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *DeleteRecipeTranslationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type DeleteRecipeTranslationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteRecipeTranslationResponse) Reset() {
	*x = DeleteRecipeTranslationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_delete_recipe_translation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecipeTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeTranslationResponse) ProtoMessage() {}

func (x *DeleteRecipeTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_recipe_translation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeTranslationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecipeTranslationResponse) Descriptor() ([]byte, []int) {
	return file_v1_delete_recipe_translation_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRecipeTranslationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_delete_recipe_translation_proto protoreflect.FileDescriptor

var file_v1_delete_recipe_translation_proto_rawDesc = []byte{
	0x0a, 0x22, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2d, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x2d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x7a, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x65, 0x70, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x6c, 0x69, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x66,
	0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_delete_recipe_translation_proto_rawDescOnce sync.Once
	file_v1_delete_recipe_translation_proto_rawDescData = file_v1_delete_recipe_translation_proto_rawDesc
)

func file_v1_delete_recipe_translation_proto_rawDescGZIP() []byte {
	file_v1_delete_recipe_translation_proto_rawDescOnce.Do(func() {
		file_v1_delete_recipe_translation_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_delete_recipe_translation_proto_rawDescData)
	})
	return file_v1_delete_recipe_translation_proto_rawDescData
}

var file_v1_delete_recipe_translation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_delete_recipe_translation_proto_goTypes = []interface{}{
	(*DeleteRecipeTranslationRequest)(nil),  // 0: v1.DeleteRecipeTranslationRequest
	(*DeleteRecipeTranslationResponse)(nil), // 1: v1.DeleteRecipeTranslationResponse
}
var file_v1_delete_recipe_translation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_delete_recipe_translation_proto_init() }
func file_v1_delete_recipe_translation_proto_init() {
	if File_v1_delete_recipe_translation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_delete_recipe_translation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecipeTranslationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_delete_recipe_translation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecipeTranslationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_delete_recipe_translation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_delete_recipe_translation_proto_goTypes,
		DependencyIndexes: file_v1_delete_recipe_translation_proto_depIdxs,
		MessageInfos:      file_v1_delete_recipe_translation_proto_msgTypes,
	}.Build()
	File_v1_delete_recipe_translation_proto = out.File
	file_v1_delete_recipe_translation_proto_rawDesc = nil
	file_v1_delete_recipe_translation_proto_goTypes = nil
	file_v1_delete_recipe_translation_proto_depIdxs = nil
}
