// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.0
// source: v1/set-recipe-favourite-status.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRecipeFavouriteStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId  string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Favourite bool   `protobuf:"varint,3,opt,name=favourite,proto3" json:"favourite,omitempty"`
}

func (x *SetRecipeFavouriteStatusRequest) Reset() {
	*x = SetRecipeFavouriteStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_set_recipe_favourite_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRecipeFavouriteStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecipeFavouriteStatusRequest) ProtoMessage() {}

func (x *SetRecipeFavouriteStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_recipe_favourite_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecipeFavouriteStatusRequest.ProtoReflect.Descriptor instead.
func (*SetRecipeFavouriteStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_set_recipe_favourite_status_proto_rawDescGZIP(), []int{0}
}

func (x *SetRecipeFavouriteStatusRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *SetRecipeFavouriteStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetRecipeFavouriteStatusRequest) GetFavourite() bool {
	if x != nil {
		return x.Favourite
	}
	return false
}

type SetRecipeFavouriteStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetRecipeFavouriteStatusResponse) Reset() {
	*x = SetRecipeFavouriteStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_set_recipe_favourite_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRecipeFavouriteStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecipeFavouriteStatusResponse) ProtoMessage() {}

func (x *SetRecipeFavouriteStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_recipe_favourite_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecipeFavouriteStatusResponse.ProtoReflect.Descriptor instead.
func (*SetRecipeFavouriteStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_set_recipe_favourite_status_proto_rawDescGZIP(), []int{1}
}

func (x *SetRecipeFavouriteStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_set_recipe_favourite_status_proto protoreflect.FileDescriptor

var file_v1_set_recipe_favourite_status_proto_rawDesc = []byte{
	0x0a, 0x24, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74, 0x2d, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2d,
	0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x73, 0x0a, 0x1f, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x69, 0x74, 0x65, 0x22,
	0x3c, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x46, 0x61, 0x76, 0x6f,
	0x75, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x70, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x6c, 0x69, 0x65, 0x2f, 0x63, 0x68, 0x65, 0x66, 0x62, 0x6f, 0x6f, 0x6b,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_set_recipe_favourite_status_proto_rawDescOnce sync.Once
	file_v1_set_recipe_favourite_status_proto_rawDescData = file_v1_set_recipe_favourite_status_proto_rawDesc
)

func file_v1_set_recipe_favourite_status_proto_rawDescGZIP() []byte {
	file_v1_set_recipe_favourite_status_proto_rawDescOnce.Do(func() {
		file_v1_set_recipe_favourite_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_set_recipe_favourite_status_proto_rawDescData)
	})
	return file_v1_set_recipe_favourite_status_proto_rawDescData
}

var file_v1_set_recipe_favourite_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_set_recipe_favourite_status_proto_goTypes = []interface{}{
	(*SetRecipeFavouriteStatusRequest)(nil),  // 0: v1.SetRecipeFavouriteStatusRequest
	(*SetRecipeFavouriteStatusResponse)(nil), // 1: v1.SetRecipeFavouriteStatusResponse
}
var file_v1_set_recipe_favourite_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_set_recipe_favourite_status_proto_init() }
func file_v1_set_recipe_favourite_status_proto_init() {
	if File_v1_set_recipe_favourite_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_set_recipe_favourite_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRecipeFavouriteStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_set_recipe_favourite_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRecipeFavouriteStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_set_recipe_favourite_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_set_recipe_favourite_status_proto_goTypes,
		DependencyIndexes: file_v1_set_recipe_favourite_status_proto_depIdxs,
		MessageInfos:      file_v1_set_recipe_favourite_status_proto_msgTypes,
	}.Build()
	File_v1_set_recipe_favourite_status_proto = out.File
	file_v1_set_recipe_favourite_status_proto_rawDesc = nil
	file_v1_set_recipe_favourite_status_proto_goTypes = nil
	file_v1_set_recipe_favourite_status_proto_depIdxs = nil
}
